services:
  db-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT_EXTERNAL}:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
    ports:
      - "${PHPMYADMIN_PORT_EXTERNAL}:80"
    depends_on:
      - db-mysql

volumes:
  db_mysql: